phase: "qa"
image:
  repository: ""
  tag: "master"
ingress:
  host: ""
  baseUrl: ""
github:
  project: ""
deployment:
  port: ""
google:
  apiKey: ""
  clientId: ""
vcs:
  ref: ""
dockerSecret: "dockerhub"
